signalfx/content-discovery

- group/AWS ELB.json
- Removed the chart "# Routed Hosts per AZ" chart since we were displaying incorrect information with the metric being returned. We cannot tell # of instances per AZ if cross-AZ load balancing is enabled per the docs https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html#loadbalancing-metrics-clb
- Added single value chart for # of Healthy Hosts total
- Added single value chart for # of Unhealthy Hosts total
> Aws elb fix

- group/AWS DynamoDB.json
Changed charts "ReadCapacityUnits" and "WriteCapacityUnits" to be "Percentage of Read Capacity Consumed" and "Percentage of Write Capacity Consumed", as they are more meaningful.
Removed the "ProvisionedReadCapacity" and "ProvisionedWriteCapacity" charts
> updated 2 charts

- group/Elasticsearch Index.json
Updated Search Latency, Index Latency, Merge Latency charts in Elasticsearch Index dashboard to use delta rather than timeshift. Verified import in lab via content-discovery-staging.
> Update ES Index charts to use delta rollup

- group/AWS Redshift.json
Update Maintenance Mode chart - 
-  Use "upper" stat instead of count
-  Update color threshold to GREEN is Maintenance mode is OFF and YELLOW if it's ON
> Update AWS Redshift group

- group/APM.json
µAPM dashboard group, with Service and Service Endpoint dashboards, along with crosslink on `service:*` to the Service dashboard.
> Add Microservices APM dashboard group (µAPM)

- group/AWS RDS.json
- Removed unnecessary DBInstanceIdentifier filter from AWS/RDS instance dashboard charts
- Updated charts in AWS/RDS instances dashboard to aggregate by `aws_account_id`, `aws_region` and `DBInstanceIdentifier` instead of just `DBInstanceIdentifier` to guarantee uniqueness across accounts and regions. This should get us the right counts in charts.
> Update AWS RDS dashboards

- group/Cloud Foundry.json
- navigators/Cloud Foundry/cf cloud controller.json
- navigators/Cloud Foundry/cf diego.json
- navigators/Cloud Foundry/cf logging.json
- navigators/Cloud Foundry/cf other services.json
- navigators/Cloud Foundry/cf service brokers.json
ES6 no longer allows querys in the form of prop:(val1 val2 val3)
so we are rewriting these to prop(val1 OR val2 OR val3). This only
seems to have been an issue for cloud foundry. The cloud foundry
dashboard discovery selectors also seem to have been off -- selectors
aren't ES queries, but they were formed as if they were, I split them
into individual selectors that are supported by the current system.
> Make content compatible with es6 queries

- group/APM.json
* Fix how error rate is calculated so it shows `0%` instead of `-%` when there are no error timeseries
* Make "Latency by endpoint" chart not be a stacked chart
> Updates to µAPM dashboards

- group/AWS DynamoDB.json
The System Errors and Write Throttle Events charts had show chart legend
eneabled but a null value the dimension to show in the legend, which caused
validation errors during imports. This change just removes the chart legend
from the two charts. A better fix is likely to configure this properly, but
we'd need data flowing into signalbuddy master org to do that, which we don't
have...
> Fix invalid data models for chart objects in dynamodb dashboard

- group/AWS Lambda.json
We were summing only on "FunctionName" which included the region aggregate for the function. I added "Resource" dimension to the sum which only exists at a per function level, not at the region or account aggregation.
> AWS Lambda: fix function overcounting in overview chart

- group/Kubernetes.json
- Add new "K8s Overview" dashboard which is a combination view of cluster, node, and pod level metrics with 5 dashboard variables to filter by Cluster, Namespace, Node, Deployment (property), and Service (tags)
- Add the same dashboard variables to the "Pods" dashboard
- Add Cluster dashboard variable to "Nodes" dashboard
- Update discovery selectors on Nodes, Pods dashboard to make them appear correctly again in dashboard discovery for infra-nav
> Update Kubernetes dashboard group

- group/AWS ECS.json
We changed some charts that used `stat:count` to `stat:mean` but did not change analytics to properly give us a "count". This fixes that.
Also cleaned up charts a bit and added suffixes and units where needed.
Also deleted two invalid charts on the ECS Cluster dashboard.
> Fix charts on ECS dashboard group

- group/ActiveMQ.json
- group/Cassandra.json
- group/Couchbase.json
- group/Docker.json
- group/Elasticsearch.json
- group/Kafka.json
- group/Memcached.json
- group/Mesos.json
- group/Mesosphere Marathon.json
- group/MongoDB.json
- group/MySQL.json
- group/NGINX.json
- group/PostgreSQL.json
- group/RabbitMQ.json
- group/Redis.json
- group/Varnish.json
- group/Zookeeper.json
replace with plugin or hostHasService when possible.
this uses a join in analytics to preserve any infrastructure stats restricted to a particular service.  this will cause performance to be worse in addition to being incorrect when host count exceeds fetch limit.
> stop using sf_hostHasService. 

- group/AWS ECS.json
This is to fix incorrect dashboard names with `FX` instead of `Fx`.
> Fix ECS dashboard name typo

- group/Kubernetes.json
Count by `kubernetes.node_ready` instead of `container_cpu_utilization` because users with large clusters may return over 10k MTSs for container_cpu_utilization, causing us to show lower value than the actual count.
> K8s: Change # of nodes charts to use different metric for counting

- navigators/Kubernetes/kubernetes pods.json
Changed to be normalized by # of cores on the machine to match the chart in the Kubernetes Pods dashboard.
> K8s Nav: change container cpu utilization calculation

- group/AWS AutoScaling.json
- group/AWS CloudFront.json
- group/AWS EBS.json
- group/AWS EC2.json
- group/AWS ELB.json
- group/AWS RDS.json
- group/AWS Route53.json
- group/ActiveMQ.json
- group/Apache.json
- group/Cassandra.json
- group/Docker.json
- group/Elasticsearch Index.json
- group/Elasticsearch.json
- group/Memcached.json
- group/Mesos.json
- group/MongoDB.json
- group/MySQL.json
- group/NGINX.json
- group/PostgreSQL.json
- group/PostgreSQLNew.json
- group/RabbitMQ.json
- group/Redis.json
- group/Varnish.json
- group/Windows IIS.json
This change ensures that no required dashboard variable has a value of "null" which gets rejected by the auto-importer. The null values have been changed to "Choose <thing>" which should also improve UX slightly by making it explicit what the user should do to have the dashboard provide useful information.
> Required dashboard variable fixes

- group/AWS Enhanced RDS Monitoring - Aurora.json
- group/AWS Enhanced RDS Monitoring - SQL Server.json
Removing the `Namespace` dimension from import qualifiers since this will be two different values depending on which version of the lambda function a user is using (`namespace` or `Namespace`). The metric name and `EngineName` are granular enough to be an import qualifier.
> Update import qualifiers

- group/Couchbase.json
`gauge.bucket.basic.dataUsed` was the previous import qualifier. This metric is not on by default. Changed to `gauge.bucket.basic.diskUsed` which should be default.
> Change import qualifer for Couchbase

- group/Consul.json
- group/Envoy.json
This PR adds an Envoy dashboard in Consul dashboard group.
You can check the dashboard on lab http://lab.corp.signalfx.com/#/dashboard/D-d_SiwAEAA
Please let me know if you need an access to the org. Thanks.
> Add consul connect envoy dashboard

- navigators/AWS/elb.json
also added `_exists_:AvailabilityZone` so that the MTSs without an availability zone (which are aggregates of all availability zones) are not added to the summations, which was causing double values for each program.
> ELB Nav: Sum by AWSUniqueId

- navigators/AWS/aws architecture.json
added a `not` AvailabilityZone:* so that the load balancer properties will appear, as this should only match 1 mts.
before, there was AvailabilityZone:* and sum by LoadBalancerName, so the properties were dropped. The MTS missing the AZ is an aggregate of the AZs already, so this value is the same.
> AWS Overview nav: change elb query

- group/Cloud Foundry.json
Add "rep.ContainerCount" as an import qualifier. The old import qualifier is based on the BOSH HM metrics, which as of PCF 2.0, have been deprecated and renamed.
> Cloud Foundry: Update import qualifier

- navigators/Hosts/collectd hosts.json
`host_cpu_cores` is reporting logical num of processors. we already report this as `host_logical_cpus`, and it's confusing people. Removing it for now.
> Hosts: resync nav and remove invalid property

- group/Smart Gateway.json
- new internal metrics description
- manually update charts with rate per second (to avoid changing of default)
- smart gateway internals has clusterSize and defaulting to all hosts
> Update smart gateway dashboards

- group/AWS Lambda.json
AWS Function Name is a required dashboard variable and charts will show incorrect values if not set. The default value was empty. This changes it to use "Choose a function"
> fix default dashboard variable

- group/APM.json
* Adds Kubernetes pods usage charts in both service and service endpoint dashboards
* Fixes error rate charts for 100% error rate scenarios by adding zero extrapolation
* Fix crosslink export (will require manual cleanup of old APM crosslinks)
> Update µAPM dashboards

- group/Azure SQL Databases.json
- group/Azure SQL Server Elastic Pools.json
- group/Azure VM Scale Sets.json
- group/Azure Virtual Machines.json
- group/Cloud Foundry.json
- group/Conviva.json
- group/Couchbase.json
- group/GitLab.json
- group/Google Cloud Spanner.json
- group/Kafka.json
- group/Knative.json
- group/Kubernetes.json
Dashboard variables with single string values that
aren't wrapped in a list cause small problems in
the UI. These changes get rid of all single string
values for built-in dashboards.
Issue: https://signalfuse.atlassian.net/browse/SQUID-1043
> Correct single string values in variables

- group/APM 2.0.json
* Group-by fixes
* Remove crosslinks that weren't meant to be there
* Use p90 response time in single value charts of RED metrics (with color)
* Add infrastructure correlation charts for hosts and K8s pods
> µAPM 2.0 dashboard updates

- group/OpenTelemetry Collector.json
This is a manual fix so the hashCode may not be valid and our logs may spit our some errors, but at least it will import correctly until the exporter is fixed.
> remove invalid crosslinks from otel collector group

- group/Kubernetes.json
The "FileSystems Usage" chart on the "K8s Containers" dashboard group had an invalid `Deployment:*` filter. This should have a matchMissing=true filter applied to it.
> fix invalid filter on k8s chart

- group/Azure Kubernetes Service.json
- Charts: # of Pods NOT in Ready state and # of Pods NOT in Ready state per namespace - Mean by Pod before count
- Chart: # of Pods by Phase- Exclude MTSes if value is zero before count
> aks: Fix certain charts

- README.md
- group/APM 2.0.json
- group/Smart Gateway.json
This changes the build-in dashbaord group from µAPM to APM for the Splunk APM rebranding.
> task(branding): rename dashboard group to APM

- group/APM 2.0.json
Leverage the combine() SignalFlow function to correctly support those
scenarios. Simplify the calculation back to an "100 * failures / requests"
base formula, but with combine() to help the join.
Also removed the stacking on the Top endpoints by error rate chart.
> apm: fix error rate charts to work when either error or non-error timeries are missing

- navigators/AWS/AWS instances.json
- navigators/AWS/awsebs.json
- navigators/AWS/awsecs.json
- navigators/AWS/cloudfront.json
- navigators/AWS/elasticache.json
- navigators/AWS/elb.json
- navigators/AWS/lambda.json
- navigators/AWS/rds databases.json
- navigators/AWS/sns.json
- navigators/AWS/sqs queues.json
Reverting the changes from the previous commit where I updated the AWS navigators, except the change to the EC2 instances nav. Also removed the "o11yMetricUnit" value from the ECS navigator.
> Updating o11y fields for AWS navigators

- navigators/Kubernetes/kubernetes pods.json
In the CPU calculation, `cpu.num_processors` is not  guaranteed to have any k8s related dimensions attached because it is reported by a separate monitor than `container_cpu_utilization`. 
By omitting the `{{filter}}` for this metric, we can still filter by k8s related properties in the first time series.
> Fix filter issue on k8s pods infra nav

- group/MongoDB.json
Starting mongo v3.3 mongodb/mongo@bba9c97 extra_info.heap_usage_bytes is no longer available the recommendation is to use tcmalloc.generic.heap_size instead
> MongoDB: Add new metric for heap usage

- group/Azure Kubernetes Service.json
reverts the previous change - https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftcontainerservicemanagedclusters - according to azure docs, this metric is the only one with the `node` dimension associated with it, so we need to count by it.
> AKS: fix num nodes chart

- navigators/Azure/azurerediscaches.json
entity-nav: Add setting where to show Azure Redis Cache
Set a value for the new setting added to the navigator 
content that will allow this nav to show up both in o11y 
and in signalview.
> RAP-551 add setting for where to show content - first test one Azure Redis Cache

- navigators/Hosts/collectd hosts.json
- navigators/Hosts/telegraf hosts.json
- navigators/Hosts/windows hosts.json
- navigators/Kubernetes/kubernetes containers.json
- navigators/Kubernetes/kubernetes nodes.json
- navigators/Kubernetes/kubernetes pods.json
entity nav: Enable Hosts+K8S Navigators for o11y
Set a value for the new setting added to the
navigator content that will allow these navs
to show up both in o11y and in signalview.
> RAP-551 Enable Hosts+K8S Navigators for o11y

- navigators/AWS/AWS instances.json
- navigators/AWS/autoscaling.json
- navigators/AWS/awsdynamodb.json
- navigators/AWS/awsebs.json
- navigators/AWS/awsecs.json
- navigators/AWS/cloudfront.json
- navigators/AWS/elasticache.json
- navigators/AWS/elb.json
- navigators/AWS/lambda.json
- navigators/AWS/rds databases.json
- navigators/AWS/sns.json
- navigators/AWS/sqs queues.json
entity nav: Enable AWS Navigators for o11y
Set a value for the new setting added to the
navigator content that will allow these navs
to show up both in o11y and in signalview.
> RAP-551 Enable AWS Navigators for o11y

- group/Kubernetes.json
apiserver_request_count is deprecated
apiserver_request_total is the replacement.
Updated signalflow on charts to use both.
> Update apiserver charts with newer metric

- group/APM 2.0.json
- group/APM Business Workflows.json
* Change the order of legend fields on the "Top endpoints by ..." charts on the Service dashboard so `sf_operation` comes first and can be cross-linked.
* Add data link on `sf_operation:*` pointing at the APM Service Endpoint dashboard.
* Exclude `sf_dimensionalized:*` timeseries for dimensionalized workflow MMS on the Workflows Overview dashboard
* Don't stack the duration chart on the Workflows Overview dashboard
* Fix the calculation of Top workflows by duration charts to not add errors and non-errors durations together (doesn't make sense for durations) and instead use a weighted average computation.
> apm: built-in content updates

- group/APM 2.0.json
- group/APM Business Workflows.json
Apply the weighted average computation program to all APM latency
charts, including on the Service and Service Endpoint dashboard to
better represent the response time across both errors and non-errors.
Also tweaked some chart descriptions on the Business Workflows Overview
dashboard.
> apm: use weighted average computation for all latency charts

- navigators/AWS/autoscaling.json
- navigators/AWS/awsdynamodb.json
- navigators/AWS/cloudfront.json
- navigators/AWS/elasticache.json
- navigators/AWS/rds databases.json
- navigators/Azure/azureappservice.json
- navigators/Azure/azurebatch.json
- navigators/Azure/azureeventhubs.json
- navigators/Azure/azurefunctions.json
- navigators/Azure/azurelogicapps.json
- navigators/Azure/azurerediscaches.json
- navigators/Azure/azuresqldatabases.json
- navigators/Azure/azurestorage.json
- navigators/Google Cloud Platform/gcp appengine.json
- navigators/Google Cloud Platform/gcp bigtable.json
- navigators/Google Cloud Platform/gcp containerengine.json
- navigators/Google Cloud Platform/gcp pubsub subscription.json
- navigators/Google Cloud Platform/gcp pubsub topic.json
- navigators/Google Cloud Platform/gcp spanner.json
- navigators/Google Cloud Platform/gcp storage.json
- navigators/Google Cloud Platform/gcp_k8s_clusters.json
Adjusted o11ySignalflowTemplate, o11yMetricName, o11yProductName fields for various navigators in preparation for GA.
Hid the AWS Autoscaling, GCP Cloud Pub/Sub, Azure Batch, and Azure Event Hubs navigators for olly by modifying the sites field.
> Updating olly fields for select navigators

- group/AWS ECS.json
- navigators/AWS/AWS instances.json
- navigators/AWS/awsebs.json
- navigators/AWS/awsecs.json
- navigators/AWS/cloudfront.json
- navigators/AWS/elasticache.json
- navigators/AWS/elb.json
- navigators/AWS/rds databases.json
- navigators/AWS/sns.json
- navigators/AWS/sqs queues.json
- navigators/Azure/azurefunctions.json
- navigators/Azure/azurerediscaches.json
- navigators/Azure/azuresqldatabases.json
- navigators/Azure/azurevirtualmachines.json
- navigators/Google Cloud Platform/gcp bigtable.json
- navigators/Google Cloud Platform/gcp cloudfunctions.json
- navigators/Google Cloud Platform/gcp compute.json
- navigators/Google Cloud Platform/gcp containerengine.json
- navigators/Google Cloud Platform/gcp spanner.json
- navigators/Google Cloud Platform/gcp_k8s_clusters.json
- navigators/Hosts/collectd hosts.json
Adjusted o11ySignalflowTemplate for various navs to bring the signalflow in line with the signalflow used for the Entity Nav heatmap.
Modified ElastiCache nav to show Running Nodes on olly landing page.
Fixed bug in ECS (AWS) dashboard so that it now shows up on the ECS Infra Navigator (underneath the heatmap).
> Update olly signalflow for navs + ECS dashboard bug fix

- group/Azure Virtual Machines.json
The new unified Azure VMs aggregate dashboard was not being displayed in the Infra Nav in olly due to faulty discoveryOptions. This PR addresses that issue.
> Fixing Azure VMs aggregate dashboard discovery

- group/Azure Virtual Machines.json
- group/Google Compute Engine.json
The new unified GCE and Azure VMs aggregate dashboards were not being displayed in the Infra Nav in olly due to their discoveryOptions. This commit addresses that issue.
> Fixing GCE, Azure VMs aggregate dashboard discovery

- group/Azure Virtual Machines.json
The new Azure VMs unified instance dashboard had a dashboard variable for azure_resource_name, but this variable isn't guaranteed to be collected from otel hosts, and it also was not being aggregated on in the heatmap signalflow, leading to issues when opening a chart from the new Entity Nav. Changed the dashboard variable to azure_resource_id instead to resolve that issue.
> Azure VMs unified instance dashboard variable change

- navigators/Hosts/hosts - my data center.json
Modify signalflow templates in the My Data Center olly nav so that SmartAgent hosts are shown as well as Otel hosts.
> Fix My Data Center olly nav to show SmartAgent hosts

- navigators/AWS/elb.json
- navigators/Kubernetes/kubernetes containers.json
- navigators/Kubernetes/kubernetes nodes.json
- navigators/Kubernetes/kubernetes pods.json
The importQualifier for the ELB navigator uses _exists_ as the property, which does not seem to be handled properly in signalbuddy, leading to the ELB nav not being imported into orgs despite sending the appropriate data.
Updating the k8s navigators importQualifiers for otel data.
> Fix importQualifiers for ELB, k8s navs

- navigators/Hosts/hosts - my data center.json
The importQualifiers for the My Data Center nav did not include "host.name", just "host"...since the mapping service isn't used on properties in the importQualifiers when determining whether to import content or not, customers that only had hosts that reported "host.name" were not seeing the My Data Center nav. This commit addresses that issue.
> Fix importQualifiers for My Data Center nav
