group/Docker.json

Docker Host dashboard had many filters like "host: i-3282934" attached
Docker Container had incorrect filter "plugin_instance: mongodb..."

remove incorrect filters for host and plugin_instance

---

group/Kubernetes.json

k8s node dashboard was appearing on incorrect windows host infra nav.

updating selector queries on k8s

---

group/MongoDB.json

mongo: Fix typo in Hosts dashboard

---

group/Elasticsearch.json

Updating import qualifier to `counter.indices.indexing.index-total`.  Mocked import in lab for testing.

Update Elasticsearch import qualifier

---

group/AWS ElastiCache.json

_missing_ no longer supported by our backend.

Replace _missing_ with NOT prop:* for elasticache dashboard

---

group/Azure Kubernetes Service.json

The hashcode doesn't seem to be the actual hashcode of the group
as it is in signalbuddy master org which is causing signalbuddy
to continuously think that this is a new package.

Reimport Azure Kubernetes Service

---

group/Smart Gateway.json

- remove sum(1m) which produces bad results for different resolutions
Issue: https://signalfuse.atlassian.net/browse/APM-1360

Update Smart Gateway dashboards

---

group/Smart Gateway.json

with num goroutines and expired buffer entries

Update smart gateway internals dashboard

---

group/Kubernetes.json

Nodes: sf_key:kubernetes_cluster --> sf_key:host
Pods:  sf_key:kubernetes_pod_name --> _exists_:kubernetes_pod_name

Update discovery selectors on Nodes and Pods dashboards

---

group/AWS ECS.json

revert back to using stat:count for counting number of tasks.

Fix ecs task count charts

---

group/Envoy.json

Add a new Envoy dashboard group. New dashboard icon was submitted to Signalview.
Issue: https://signalfuse.atlassian.net/browse/INT-1039

Add group Envoy

---

group/Azure Kubernetes Service.json

`resource_type:Microsoft.ContainerService/managedClusters` added to import qualifier.

Add dimension to import qualifier on AKS group

---

group/AWS Kinesis Analytics.json

Fixed `Record Received in the Past` chart in overview dashboard

Fix Kinesis Analytics Dashboard

---

group/AWS Enhanced RDS Monitoring.json

to match what the lambda function emits

Add import qualfier on RDS enhanced

---

group/Windows IIS.json

Added analytics on heatmap charts to "sum by instance,host"

Windows IIS: Update heatmap chart

---

group/Smart Gateway.json

Issue: https://signalfuse.atlassian.net/browse/APMB-228

Update smart gateway dashboard version chart

---

group/Sample Data.json

Update sample data link

---

group/Smart Gateway.json

This changelist updates the description of internal metrics on smart gateway internal dashboard
Issue: https://signalfuse.atlassian.net/browse/APMB-260

Updating smart gateway dashboard internal metrics description

---

group/Smart Gateway.json

removal of instance dashboard
addition of 2.0 channel sizes in buffer size chart on internals
addition of optional cluster dashboard variable in internals

Update smart gateway dashboards group

---

group/Infrastructure.json

Reverts signalfx/content-discovery#106

Revert "Infrastructure: Fix discovery query"

---

navigators/Hosts/collectd hosts.json

Reverts signalfx/content-discovery#105

Revert "Hosts: resync nav and remove invalid property"

---

group/Smart Gateway.json

1) Adding debug traces to retained tpm
2) Adding gateway.dropped_spans to dropped spans chart
3) Adding gateway.dropped_traces and debug.overSizeLimit traces to dropped traces chart

Smart gateway internal dashboard update for v2

---

group/Infrastructure.json
navigators/Hosts/collectd hosts.json

Somehow the nav view got out of sync with SBMO. Resyncing that, but needed to update the discovery query on the dashboard for it to still show up for the infra nav.

Resync host nav and dashboard

---

group/Logstash.json

You can see it on lab here
http://lab.corp.signalfx.com/#/dashboard/EEMyTV0AAZ4?startTimeUTC=1568226881000&endTimeUTC=1568226999000
Thanks!

Add logstash dashboard

---

navigators/Cloud Foundry/cf cloud controller.json
navigators/Cloud Foundry/cf diego.json
navigators/Cloud Foundry/cf instances.json
navigators/Cloud Foundry/cf logging.json
navigators/Cloud Foundry/cf other services.json
navigators/Cloud Foundry/cf service brokers.json

Tested each locally against prod by running signalview.

Update Cloud Foundry navs to be compatible with PCF v>=2.0

---

group/AWS Lambda.json

Refactored AWS Function and AWS Overview dashboards (not wrapper)
- Added a few new AWS metrics for provisioned lambdas
- Added units for all charts

Refactor lambda dashboard & add new metrics

---

group/ActiveMQ.json
group/NGINX.json
group/Redis.json
group/Varnish.json

Several dashboards had invalid filters that were left over from who ever created the charts. This removes them.

Remove invalid filters on several charts

---

README.md
group/ActiveMQ.json
group/NGINX.json
group/Redis.json
group/Varnish.json

* add rollups to charts with counters for 4 groups

add roll up of rate to charts whose metrics are counters (#163)

---

README.md
group/ActiveMQ.json
group/NGINX.json
group/Redis.json
group/Varnish.json
group/Zookeeper.json

clean up Zookeeper dashboard and add default rollups

resync lab with master

---

group/Cassandra.json
group/CouchDB.json
group/Hadoop HDFS.json
group/Kong.json

- cassandra
- kong
- hadoop hdfs
- couchdb

clean up dashboards and add default rollups

---

group/Cassandra.json
group/CouchDB.json
group/Hadoop HDFS.json
group/Kong.json
group/Zookeeper.json

cleaned up invalid filters and added more default rollups on the following dashboards:
- cassandra
- hadoop HDFS
- couchdb
- kong

resync master with lab

---

group/APM 2.0.json
group/Sample Data.json

Issue: https://signalfuse.atlassian.net/browse/INT-1784

update support email address

---

group/APM 2.0.json

µAPM 2.0: Remove HTTP method dashboard variable

---

group/APM 2.0.json
group/APM.json

Verified in Lab, ready for prod.

Merge lab into master

---

group/Kubernetes.json

- Add new local datalinks for each k8s dashboard
- Remove invalid "minikube" filter on two etcd plots on the k8s services dashboard

Add k8s local datalinks

---

group/Kubernetes.json

Reverts signalfx/content-discovery#187

Revert "Add k8s local datalinks"

---

group/APM 2.0.json

K8s dashboard improvements
- Removed invalid "minikube" filter on two ETCD charts
- Add several local datalinks

Merge lab changes into master

---

group/Kubernetes.json
group/OpenTelemetry Collector.json

- Removed invalid crosslinks in the OpenTelemetry Collector dashboard group

Rebase master with lab

---

navigators/Google Cloud Platform/gcp_k8s_clusters.json
navigators/Google Cloud Platform/gcp_k8s_nodes.json
navigators/Google Cloud Platform/gcp_k8s_pods.json

GKE clusters
GKE nodes
GKE pods

Add 3 new gke infra navs

---

navigators/Google Cloud Platform/gcp_k8s_clusters.json
navigators/Google Cloud Platform/gcp_k8s_nodes.json
navigators/Google Cloud Platform/gcp_k8s_pods.json

GKE clusters
GKE nodes
GKE pods

Add 3 new GKE infra nav views

---

group/Kubernetes.json

Invalid because pending or unknown pod status may be not assigned to a node yet

Remove node filter from pod phase metric

---

group/APM 2.0.json
group/Kubernetes.json
navigators/Kubernetes/kubernetes nodes.json

Reverts signalfx/content-discovery#209
Kubernetes nodes new signalflow does not behave nicely because of the union

Revert "merge lab into master"

---

group/Kubernetes.json

Also undo'ing change for discovery selectors

k8s: update import qualifier

---

navigators/Azure/azurevirtualmachines.json
navigators/Containers/Docker containers.json

Small change to Azure VMs navigator just for testing purposes (will not go into master).

Testing navigator changes

---

navigators/Azure/azurevirtualmachines.json

Reverting the Azure VMs nav changes.

Reverting changes made for testing

---

group/Cloud Foundry.json
navigators/Google Cloud Platform/gcp_k8s_clusters.json
navigators/Google Cloud Platform/gcp_k8s_nodes.json
navigators/Google Cloud Platform/gcp_k8s_pods.json

- Updated all k8s infra navs for otel metrics & backwards compatibility for kubelet-metrics / kubelet-stats
- Updated k8s nodes dashboard selectors for k8s nav changes
All changes tested locally and in lab.

release lab content to prod

---

README.md
group/APM 2.0.json
group/Smart Gateway.json

This changes the build-in dashbaord group from µAPM
to APM.
Issue: https://signalfuse.atlassian.net/browse/APMF-2155

task(branding): rename dashboard group to APM

---

README.md
group/APM 2.0.json
group/Smart Gateway.json

Reverts signalfx/content-discovery#228

Revert "task(branding): rename dashboard group to APM"

---

group/Azure Kubernetes Service.json

Reverts signalfx/content-discovery#232. Updates didn't go as expected in lab. Will submit another PR, once I figure out what's going on.

Revert "aks: Fix certain charts"

---

navigators/Azure/azurevirtualmachines.json

Added new fields to Azure Virtual Machines navigator for use in o11y UI.

Adding new navigator fields for use in o11y

---

navigators/Azure/azurevirtualmachines.json

Changing hash code so that previous changes to this nav get picked up (did not get picked up before due to serialization error).

Adding new o11y specific fields to Azure VMs nav

---

navigators/AWS/AWS instances.json
navigators/AWS/autoscaling.json
navigators/AWS/awsdynamodb.json
navigators/AWS/awsebs.json
navigators/AWS/awsecs.json
navigators/AWS/cloudfront.json
navigators/AWS/elasticache.json
navigators/AWS/elb.json
navigators/AWS/lambda.json
navigators/AWS/rds databases.json
navigators/AWS/sns.json
navigators/AWS/sqs queues.json
navigators/Azure/azureappservice.json
navigators/Azure/azurebatch.json
navigators/Azure/azureeventhubs.json
navigators/Azure/azurefunctions.json
navigators/Azure/azurelogicapps.json
navigators/Azure/azurerediscaches.json
navigators/Azure/azuresqldatabases.json
navigators/Azure/azurestorage.json
navigators/Google Cloud Platform/gcp appengine.json
navigators/Google Cloud Platform/gcp bigtable.json
navigators/Google Cloud Platform/gcp cloudfunctions.json
navigators/Google Cloud Platform/gcp compute.json
navigators/Google Cloud Platform/gcp containerengine.json
navigators/Google Cloud Platform/gcp pubsub subscription.json
navigators/Google Cloud Platform/gcp pubsub topic.json
navigators/Google Cloud Platform/gcp spanner.json
navigators/Google Cloud Platform/gcp storage.json
navigators/Google Cloud Platform/gcp_k8s_clusters.json

Adding new fields to the AWS/Azure/GCP navs to support a tailored UX specific to o11y.

Adding new o11y specific fields to AWS/Azure/GCP navs

---

navigators/Kubernetes/kubernetes containers.json
navigators/Kubernetes/kubernetes nodes.json
navigators/Kubernetes/kubernetes pods.json

Adding this as a filterProperty seemingly fixed the linking issues.

update k8s infra navs with k8s nodes filter properties

---

navigators/Hosts/collectd hosts.json
navigators/Kubernetes/kubernetes containers.json
navigators/Kubernetes/kubernetes nodes.json
navigators/Kubernetes/kubernetes pods.json

Adding new fields to the kubernetes and collectd navs to support a tailored UX specific to o11y.

Adding new o11y specific fields to k8s/collectd navs

---

group/Azure Kubernetes Service.json

- also added a "sum()" to the "Allocatable CPU Cores" single value chart

AKS: Change metric to count number of nodes

---

navigators/Azure/azurefunctions.json

entity nav: Enable Azure Function Apps for o11y
Set a value for the new setting added to the
navigator content that will allow this nav
to show up both in o11y and in signalview.

RAP-551 Enable Azure Function Apps for o11y

---

navigators/Azure/azureappservice.json
navigators/Azure/azurebatch.json
navigators/Azure/azureeventhubs.json
navigators/Azure/azurefunctionssignalfx.json
navigators/Azure/azurelogicapps.json
navigators/Azure/azuresqldatabases.json
navigators/Azure/azurestorage.json
navigators/Azure/azurevirtualmachines.json

entity nav: Enable Other Azure Navigators for o11y  
Set a value for the new setting added to the
navigator content that will allow these navs 
to show up both in o11y and in signalview.  

RAP-551 azure remaining navs to o11y

---

navigators/Google Cloud Platform/gcp appengine.json
navigators/Google Cloud Platform/gcp bigtable.json
navigators/Google Cloud Platform/gcp cloudfunctions.json
navigators/Google Cloud Platform/gcp compute.json
navigators/Google Cloud Platform/gcp containerengine.json
navigators/Google Cloud Platform/gcp pubsub subscription.json
navigators/Google Cloud Platform/gcp pubsub topic.json
navigators/Google Cloud Platform/gcp spanner.json
navigators/Google Cloud Platform/gcp storage.json
navigators/Google Cloud Platform/gcp_k8s_clusters.json
navigators/Google Cloud Platform/gcp_k8s_nodes.json
navigators/Google Cloud Platform/gcp_k8s_pods.json

entity nav: Enable GCP Navigators for o11y  
Set a value for the new setting added to the 
navigator content that will allow these navs 
to show up both in o11y and in signalview.  

RAP-551 gcp navs to o11y

---

navigators/AWS/AWS Instances - unified.json
navigators/Azure/Azure VMs - Unified.json
navigators/Azure/azurefunctions.json
navigators/Azure/azurelogicapps.json
navigators/Google Cloud Platform/gcp appengine.json
navigators/Google Cloud Platform/gcp cloudfunctions.json
navigators/Google Cloud Platform/gcp compute - unified.json
navigators/Google Cloud Platform/gcp containerengine.json

Updated navigator metric resolutions such that all metrics for a given cloud platform (AWS, Azure, GCP) have the same resolution, to ensure data consistency in olly.
Also updated landing card signalflow for the few new navigators for olly.

Update navigator metric resolutions, signalflow for olly

---

group/AWS EBS.json
group/AWS EC2.json
group/AWS ECS.json
group/AWS ELB.json
group/AWS Lambda.json
group/AWS RDS.json
group/AWS SNS.json
group/AWS SQS.json
group/Azure Functions.json
group/Azure Virtual Machines.json
group/Datacenter Hosts.json
group/Google Compute Engine.json
group/Google Kubernetes Engine.json

Updated various (single value) charts across dashboard groups to improve consistency between the value shown on the single value charts and the number of elements shown on the heatmap.

Update charts for consistency with infra nav heatmap

---

group/AWS CloudFront.json
group/AWS EBS.json
group/AWS ECS.json
group/AWS ELB.json
group/AWS ElastiCache.json
group/AWS RDS.json
group/AWS SNS.json
group/AWS SQS.json
group/Azure Functions.json
group/Azure Redis Caches.json
group/Datacenter Hosts.json
group/Google Cloud Bigtable.json
group/Google Compute Engine.json
group/Google Container Engine.json
group/Google Kubernetes Engine.json

Updated various (single value) charts to improve consistency between the value shown on the single value charts and the number of elements shown on the heatmap.

Infra nav chart program text consistency updates

---

group/Azure Virtual Machines.json

Fixed an issue where the single instance dashboard for Azure VMs was not being discovered for some instances in olly (due to them being Virtual Machine Scale Sets).

Fixing Azure VMs instance dashboard discovery

---

group/Data Center Hosts.json

add top to vmem chart

---

group/Azure Virtual Machines.json

tested in lab ✅ 
group id same ✅ 
hashcode different ✅

Add chart description to otel only charts on azure vms dashboard

---

group/Data Center Hosts.json

add host.name selector for Datacenter Hosts dashboard

---

group/AWS Lambda.json

test of https://github.com/signalfx/content-discovery/pull/349/files in lab

Update the name of the cause field in the lambda extensions charts (lab)
